spring:
  application:
    name: urfu
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/urfu
    username: postgres
    password: postgres
  mvc:
    view:
      suffix: .html

logging:
  file:
    path: logs
    name: ${logging.file.path}/${spring.application.name}.log
  level:
    ru:
      hostco: info
    root: info
  pattern:
    file: '"%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"'